### ISSUE TITLE
Position of button

### ISSUE THREAD

**Issue by niodx** [alekslt/DSPPlugins_ALT#2]
A configuration for button position is better if it's possible. sometime I just too lazy for alt+I, so I like to click the button. but it's kinda conflict with the time.
or change the button to the middle right of tech button if you don't want to do much coding.
anything is ok, really appreaciate that.

Thank you for your work.

**Comment by alekslt** [comment]
Ah! I see that the button placement calculation is a bit off now. Moving it over to the right of tech button does make more sense, so I'll probably do that as well, as looking into doing a customizable position.

**Comment by alekslt** [comment]
Fix available in release 0.5.1 https://dsp.thunderstore.io/package/alekslt/MineralExhaustionNotifier/0.5.1/
