### ISSUE TITLE
1600 missing from UI height list

### ISSUE THREAD

**Issue by van-dell** [alekslt/DSPPlugins_ALT#5]
Glad I found the mod, thanks!

However, us 16:10 folks are sometimes a bit overlooked :-D 1600 is missing from the accepted config options despite being available ingame _if_ the current resolution is ...x1600. Could you add that in? Looks like my resolution got changed to 2560x1440 as well, but am not sure if that was the mod or something else.

Thanks!

**Comment by alekslt** [comment]
Hey, sorry for late reply, last weeks have been quite hectic. So I changed the implementation in v0.2 now to work more in-line with the game. So upgrade to v0.2 and set your wanted resolution in the game once, and it should stick now. 
Can be downloaded from https://github.com/alekslt/DSPPlugins_ALT/releases/tag/UILayoutHeightFix-v0.2 or through https://dsp.thunderstore.io/package/alekslt/UILayoutHeightFix/
